baseurl: "https://frankzheng.me"
languageCode: "en-us"
title: "Frank Zheng | 郑翔"
theme: "hugo-ivy"
disqusShortname: "frank"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "我"
      url: "/cn/about/"
      weight: 3
    - name: "想"
      url: "/cn/"
      weight: 4
  en:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 3
    - name: "中文"
      url: "/cn/"
      weight: 4
  cn:
    - name: "我"
      url: "/cn/about/"
      weight: 1
    - name: "想"
      url: "/cn/"
      weight: 2
    - name: "历"
      url: "/cn/vitae/"
      weight: 3
    - name: "厨"
      url: "/cn/recipe/"
      weight: 4
    - name: "健"
      url: "/fitness/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6


params:
  description: "Personal website of Frank Zheng; 郑翔的个人网站"
  footer: "&copy; [Frank Zheng](/) 2019"
  disqusURL: "https://frankzheng.me"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/Frankxz/frankzheng.me/edit/master/content/"
  #twitterImage: "/images/logo.png"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo.png"
      url: "/"
      alt: "Frank Zheng"
      tag: ""

  author:
    en: "Frank Zheng"
    cn: "郑翔"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"

      
  blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
